import uuid
from sqlalchemy import text
from app.db.session import engine
from app.core.logger import logger
from app.models.base import Base
import app.models.categoria
import app.models.transaccion
import app.models.regla_recurrente
import app.models.onboarding

class TenantManager:
    @staticmethod
    def generate_tenant_name(user_id: int) -> str:
        random_suffix = uuid.uuid4().hex[:8]
        return f"tenant_user_{user_id}_{random_suffix}"

    @staticmethod
    async def create_tenant_schema(schema_name: str) -> None:
        async with engine.begin() as conn:
            try:
                # DDL like CREATE SCHEMA cannot be easily parameterized in standard SQLAlchemy binds.
                # However, schema_name is purely generated by our uuid and safe ints.
                # Still, escaping it is a good practice if it ever changed.
                # For schema names in PostgreSQL, we must use identifiers properly.
                safe_schema = schema_name.replace('"', '""')
                await conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{safe_schema}"'))

                # set search_path with bindparams works in modern asyncpg
                # however, DDL/Config often prefers string formatting if strictly controlled.
                await conn.execute(text(f'SET search_path TO "{safe_schema}"'))

                tables_to_create = [
                    Base.metadata.tables[table_name]
                    for table_name in Base.metadata.tables
                    if table_name != "usuarios"
                ]

                await conn.run_sync(Base.metadata.create_all, tables=tables_to_create)
            except Exception as e:
                logger.error(f"Fallo crítico al crear el tenant schema '{schema_name}': {str(e)}")
                raise
